### ISSUE TITLE
📢 Claude通知ボード

### ISSUE THREAD

**Issue by ibushimaru** [ibushimaru/github-mcp-test-playground#2]
## 自動通知システム

このIssueは、GitHub ActionsからClaudeへの通知を管理するためのボードです。

### 使い方
1. GitHub Actionsが完了時にこのIssueにコメントを追加
2. Claudeが定期的にこのIssueのコメントをチェック
3. 新しいコメントがあれば通知として処理

### 通知フォーマット
```json
{
  "timestamp": "2025-06-13T07:45:00Z",
  "workflow": "CI/CD Pipeline",
  "status": "completed",
  "details": "All tests passed"
}
```

**Comment by ibushimaru** [comment]
## 🐛 ワークフローファイルの修正が必要

**問題**: `.github/workflows/notify-claude.yml`の69行目でYAMLシンタックスエラーが発生しています。

**原因**: JavaScriptのscriptブロックが適切に閉じられていません。

**修正方法**:
1. GitHub上で`.github/workflows/notify-claude.yml`を編集
2. ファイルの最後が以下のようになっていることを確認：

```yaml
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 2,
              body: body
            });
```

3. もし追加のインデントや文字がある場合は削除
4. ファイルを保存してコミット

**注意**: ワークフローファイルの更新には`workflow`スコープの権限が必要なため、GitHub UIから直接編集することをお勧めします。
